import { calculators, type CalculatorConfig, type CalculatorSlug } from "@/lib/calculators";

export type CalculatorGroup = "labor" | "loan" | "tax" | "investment" | "health" | "daily" | "life" | "game" | "business" | "math";

export const CALCULATOR_GROUP_META: Record<
  CalculatorGroup,
  { label: string; description: string; icon: string; accentClass: string; softClass: string }
> = {
  labor: {
    label: "급여·노무",
    description: "급여, 퇴직, 휴가, 육아휴직, 연령·복무 관련 계산기",
    icon: "💼",
    accentClass: "text-[#0f766e]",
    softClass: "bg-[#dff7f1]"
  },
  loan: {
    label: "대출·부동산",
    description: "대출, 상환, 주거비, 취득세, 환율·금융비용 계산기",
    icon: "🏦",
    accentClass: "text-[#1d4ed8]",
    softClass: "bg-[#e3efff]"
  },
  tax: {
    label: "절세·저축",
    description: "세금, 연금, ISA, 적금, 예금 계산기",
    icon: "📊",
    accentClass: "text-[#7c3aed]",
    softClass: "bg-[#efe7ff]"
  },
  investment: {
    label: "투자·주식",
    description: "주식 수익률, 암호화폐 투자 성장, 물타기, PER/PBR 가치평가 계산기",
    icon: "↗",
    accentClass: "text-[#047857]",
    softClass: "bg-[#dcfce7]"
  },
  health: {
    label: "건강·운동",
    description: "BMI, 칼로리, 기초대사량, 수면, 러닝, 운동 중량 계산기",
    icon: "＋",
    accentClass: "text-[#be123c]",
    softClass: "bg-[#ffe4e6]"
  },
  daily: {
    label: "일상 도구",
    description: "날짜, D-day, 단위변환, 퍼센트, 할인율, 텍스트, 비밀번호 도구",
    icon: "⌁",
    accentClass: "text-[#4338ca]",
    softClass: "bg-[#e0e7ff]"
  },
  life: {
    label: "생활 도구",
    description: "반려동물, 교통, 지원금, 생활비, 취미 관련 계산기",
    icon: "🧰",
    accentClass: "text-[#c2410c]",
    softClass: "bg-[#fff0e3]"
  },
  game: {
    label: "게임",
    description: "가챠 확률, 포커 승률, 게임 승률, eDPI, 마우스 감도 변환 도구",
    icon: "🎮",
    accentClass: "text-[#7c2d12]",
    softClass: "bg-[#ffedd5]"
  },
  business: {
    label: "사업·판매",
    description: "판매 수익, 원가율, 손익분기점, 운영비 비교 계산기",
    icon: "📈",
    accentClass: "text-[#b42318]",
    softClass: "bg-[#fde7e4]"
  },
  math: {
    label: "수학 도구",
    description: "그래핑, 공학용, 행렬, 기하, 3D, 웹 계산 도구",
    icon: "∑",
    accentClass: "text-[#0369a1]",
    softClass: "bg-[#e0f2fe]"
  }
};

export const CALCULATOR_ICON_BY_SLUG: Record<CalculatorSlug, string> = {
  "minimum-wage": "₩",
  "unpaid-wage": "⚠",
  unemployment: "🧾",
  severance: "🎁",
  "weekly-holiday": "📅",
  "hourly-wage": "⏱",
  "annual-leave": "🌴",
  "annual-leave-grant": "🗓",
  "parental-leave": "👶",
  "net-salary": "💳",
  "military-discharge-date": "🎖",
  "loan-interest": "🏦",
  "loan-dsr": "📉",
  "loan-amortization": "📆",
  "apr-calculator": "%",
  "housing-subscription": "🏘",
  "real-estate-acquisition-tax": "🏠",
  "jeonse-vs-monthly-rent": "🏘",
  "exchange-rate": "💱",
  "card-installment": "💳",
  "youth-future-savings": "🌱",
  savings: "💰",
  "lump-sum-deposit": "🏛",
  "compound-interest": "📈",
  "pension-tax": "👵",
  "survivor-pension": "🛡",
  "comprehensive-income-tax": "📑",
  "earned-income-tax": "💼",
  "year-end-tax-settlement": "🧮",
  "inheritance-tax": "🏛",
  "isa-tax": "🧺",
  "youth-leap-account": "🚀",
  "earned-income-tax-credit": "🎯",
  "retirement-income-tax": "🏖",
  "kr-etf": "ETF",
  "stock-return": "📊",
  "coin-profit-calculator": "🪙",
  "stock-average-price": "⚖",
  "stock-valuation": "🔎",
  "crypto-investment-growth": "₿",
  "gold-price-calculator": "🥇",
  "silver-price-calculator": "🥈",
  "inflation-calculator": "🎈",
  "money-value-calculator": "⌛",
  "roi-calculator": "↗",
  "present-value": "⏳",
  bmi: "⚕",
  "bmr-calculator": "🔥",
  "ideal-weight": "⚖",
  "one-rep-max": "🏋",
  "sleep-calculator": "🌙",
  "running-pace": "🏃",
  "calorie-calculator": "🍽",
  "daily-intake": "🥗",
  "ovulation-calculator": "🌸",
  "pregnancy-week-calculator": "🤰",
  "pet-age": "🐾",
  "korean-age": "🎂",
  "anniversary-calculator": "💝",
  "milestone-birthday": "🎉",
  "lunar-solar-converter": "🌗",
  "zodiac-sign": "✨",
  "unit-converter": "📏",
  "date-diff": "📆",
  dday: "D",
  "date-add": "+",
  stopwatch: "⏱",
  "internet-speed-test": "📡",
  "pyeong-converter": "㎡",
  "random-number": "🎲",
  "draw-probability": "🎰",
  "blox-fruits-calculator": "🍍",
  "lineage-classic-hunting-efficiency": "⚔",
  "lineage-classic-lucky-character": "🛡",
  "robux-calculator": "🟩",
  "clash-of-clans-calculator": "🏰",
  "lol-skill-haste": "⚡",
  "diablo3-gem-calculator": "💎",
  "fc-transfer-fee": "⚽",
  "win-rate-calculator": "🏆",
  "edpi-calculator": "🖱",
  "mouse-sensitivity-converter": "🎯",
  "text-counter": "✍",
  "tip-calculator": "🍽",
  "poker-equity-calculator": "♠",
  "spending-habit-score": "🛍",
  "salary-vanish-calculator": "💸",
  "password-generator": "🔐",
  percent: "%",
  "discount-rate": "🏷",
  "distance-calculator": "📍",
  "traffic-fine-penalty": "🚦",
  "vehicle-inspection-period": "🚗",
  "fuel-cost": "⛽",
  "kpass-refund": "🚇",
  "childbirth-grant": "🍼",
  "lotto-generator": "🎟",
  vat: "🧾",
  "car-maintenance": "🔧",
  "auto-installment": "🚘",
  "moving-cost": "📦",
  "mobile-plan": "📱",
  "seller-profit": "🛒",
  "adsense-revenue": "Ad",
  "youtube-ad-revenue": "▶",
  "break-even": "⚖",
  "subscription-revenue": "🔁",
  "cbm-freight": "🚚",
  "real-estate-brokerage-fee": "🏡",
  "property-tax": "🏘",
  "loan-prepayment": "⏩",
  "refinance-calculator": "🔄",
  "credit-card-payoff": "💳",
  "retirement-savings": "🏦",
  "rental-property-roi": "🏢",
  "fire-retirement-age": "🔥",
  gpa: "🎓",
  "school-grade": "🏫",
  "kinship-calculator": "👪",
  "graphing-calculator": "📈",
  "scientific-calculator": "🔬",
  "four-function-calculator": "＋",
  "math-notes": "📓",
  "matrix-calculator": "▦",
  "derivative-calculator": "d/dx",
  "integral-calculator": "∫",
  "quadratic-formula": "x²",
  "factoring-calculator": "因",
  "logarithm-calculator": "log",
  "inequality-calculator": "≤",
  "standard-deviation": "σ",
  "geometry-tool": "△",
  "three-d-calculator": "3D",
  "web-calculator": "⌨"
};

const GROUP_BY_SLUG: Record<CalculatorSlug, CalculatorGroup> = {
  "minimum-wage": "labor",
  "unpaid-wage": "labor",
  unemployment: "labor",
  severance: "labor",
  "weekly-holiday": "labor",
  "hourly-wage": "labor",
  "annual-leave": "labor",
  "annual-leave-grant": "labor",
  "parental-leave": "labor",
  "net-salary": "labor",
  "military-discharge-date": "labor",
  "loan-interest": "loan",
  "loan-dsr": "loan",
  "loan-amortization": "loan",
  "apr-calculator": "loan",
  "housing-subscription": "loan",
  "real-estate-acquisition-tax": "loan",
  "jeonse-vs-monthly-rent": "loan",
  "exchange-rate": "loan",
  "card-installment": "loan",
  "youth-future-savings": "tax",
  savings: "tax",
  "lump-sum-deposit": "tax",
  "compound-interest": "tax",
  "pension-tax": "tax",
  "survivor-pension": "tax",
  "comprehensive-income-tax": "tax",
  "earned-income-tax": "tax",
  "year-end-tax-settlement": "tax",
  "inheritance-tax": "tax",
  "isa-tax": "tax",
  "youth-leap-account": "tax",
  "earned-income-tax-credit": "tax",
  "retirement-income-tax": "tax",
  "kr-etf": "investment",
  "stock-return": "investment",
  "coin-profit-calculator": "investment",
  "stock-average-price": "investment",
  "stock-valuation": "investment",
  "crypto-investment-growth": "investment",
  "gold-price-calculator": "investment",
  "silver-price-calculator": "investment",
  "inflation-calculator": "investment",
  "money-value-calculator": "investment",
  "roi-calculator": "investment",
  "present-value": "investment",
  bmi: "health",
  "bmr-calculator": "health",
  "ideal-weight": "health",
  "one-rep-max": "health",
  "sleep-calculator": "health",
  "running-pace": "health",
  "calorie-calculator": "health",
  "daily-intake": "health",
  "ovulation-calculator": "health",
  "pregnancy-week-calculator": "health",
  "pet-age": "life",
  "korean-age": "daily",
  "anniversary-calculator": "daily",
  "milestone-birthday": "daily",
  "lunar-solar-converter": "daily",
  "zodiac-sign": "daily",
  "unit-converter": "daily",
  "date-diff": "daily",
  dday: "daily",
  "date-add": "daily",
  stopwatch: "daily",
  "internet-speed-test": "daily",
  "pyeong-converter": "daily",
  "random-number": "game",
  "draw-probability": "game",
  "blox-fruits-calculator": "game",
  "lineage-classic-hunting-efficiency": "game",
  "lineage-classic-lucky-character": "game",
  "robux-calculator": "game",
  "clash-of-clans-calculator": "game",
  "lol-skill-haste": "game",
  "diablo3-gem-calculator": "game",
  "fc-transfer-fee": "game",
  "win-rate-calculator": "game",
  "edpi-calculator": "game",
  "mouse-sensitivity-converter": "game",
  "text-counter": "daily",
  "tip-calculator": "life",
  "poker-equity-calculator": "game",
  "spending-habit-score": "life",
  "salary-vanish-calculator": "life",
  "password-generator": "daily",
  percent: "daily",
  "discount-rate": "daily",
  "distance-calculator": "daily",
  "traffic-fine-penalty": "life",
  "vehicle-inspection-period": "life",
  "fuel-cost": "life",
  "kpass-refund": "life",
  "childbirth-grant": "life",
  "lotto-generator": "tax",
  vat: "business",
  "car-maintenance": "business",
  "auto-installment": "business",
  "moving-cost": "business",
  "mobile-plan": "business",
  "seller-profit": "business",
  "adsense-revenue": "business",
  "youtube-ad-revenue": "business",
  "break-even": "business",
  "subscription-revenue": "business",
  "cbm-freight": "business",
  "real-estate-brokerage-fee": "loan",
  "property-tax": "loan",
  "loan-prepayment": "loan",
  "refinance-calculator": "loan",
  "credit-card-payoff": "loan",
  "retirement-savings": "investment",
  "rental-property-roi": "investment",
  "fire-retirement-age": "investment",
  gpa: "daily",
  "school-grade": "daily",
  "kinship-calculator": "daily",
  "graphing-calculator": "math",
  "scientific-calculator": "math",
  "four-function-calculator": "math",
  "math-notes": "math",
  "matrix-calculator": "math",
  "derivative-calculator": "math",
  "integral-calculator": "math",
  "quadratic-formula": "math",
  "factoring-calculator": "math",
  "logarithm-calculator": "math",
  "inequality-calculator": "math",
  "standard-deviation": "math",
  "geometry-tool": "math",
  "three-d-calculator": "math",
  "web-calculator": "math"
};

export function getCalculatorGroup(slug: CalculatorSlug): CalculatorGroup {
  return GROUP_BY_SLUG[slug];
}

export function getCalculatorIcon(slug: CalculatorSlug) {
  return CALCULATOR_ICON_BY_SLUG[slug] ?? CALCULATOR_GROUP_META[getCalculatorGroup(slug)].icon;
}

export function getCalculatorsByGroup(group: CalculatorGroup) {
  return calculators.filter((calculator) => getCalculatorGroup(calculator.slug) === group);
}

export function getFeaturedCalculators() {
  const featuredSlugs: CalculatorSlug[] = [
    "minimum-wage",
    "unpaid-wage",
    "year-end-tax-settlement",
    "earned-income-tax",
    "inheritance-tax",
    "unemployment",
    "loan-dsr",
    "housing-subscription",
    "derivative-calculator",
    "integral-calculator",
    "quadratic-formula",
    "factoring-calculator",
    "logarithm-calculator",
    "inequality-calculator",
    "apr-calculator",
    "credit-card-payoff",
    "retirement-savings",
    "rental-property-roi",
    "inflation-calculator",
    "money-value-calculator",
    "roi-calculator",
    "pension-tax",
    "survivor-pension",
    "youth-future-savings",
    "earned-income-tax-credit",
    "kpass-refund",
    "childbirth-grant",
    "lotto-generator",
    "kr-etf",
    "crypto-investment-growth",
    "gold-price-calculator",
    "silver-price-calculator",
    "coin-profit-calculator",
    "stock-return",
    "seller-profit",
    "adsense-revenue",
    "youtube-ad-revenue",
    "calorie-calculator",
    "bmr-calculator",
    "ideal-weight",
    "one-rep-max",
    "sleep-calculator",
    "running-pace",
    "daily-intake",
    "ovulation-calculator",
    "pregnancy-week-calculator",
    "school-grade",
    "kinship-calculator",
    "pet-age",
    "military-discharge-date",
    "anniversary-calculator",
    "milestone-birthday",
    "lunar-solar-converter",
    "zodiac-sign",
    "traffic-fine-penalty",
    "vehicle-inspection-period",
    "auto-installment",
    "fuel-cost",
    "blox-fruits-calculator",
    "lineage-classic-hunting-efficiency",
    "lineage-classic-lucky-character",
    "robux-calculator",
    "clash-of-clans-calculator",
    "lol-skill-haste",
    "diablo3-gem-calculator",
    "fc-transfer-fee",
    "win-rate-calculator",
    "kpass-refund",
    "childbirth-grant",
    "draw-probability",
    "edpi-calculator",
    "mouse-sensitivity-converter",
    "text-counter",
    "tip-calculator",
    "poker-equity-calculator",
    "spending-habit-score",
    "salary-vanish-calculator",
    "fire-retirement-age",
    "password-generator",
    "date-diff",
    "vat"
  ];

  return featuredSlugs
    .map((slug) => calculators.find((calculator) => calculator.slug === slug))
    .filter(Boolean) as CalculatorConfig[];
}

export function getPopularCalculators() {
  const popularSlugs: CalculatorSlug[] = [
    "minimum-wage",
    "unpaid-wage",
    "unemployment",
    "severance",
    "derivative-calculator",
    "integral-calculator",
    "factoring-calculator",
    "logarithm-calculator",
    "loan-dsr",
    "housing-subscription",
    "credit-card-payoff",
    "inflation-calculator",
    "money-value-calculator",
    "vat",
    "exchange-rate",
    "calorie-calculator",
    "bmr-calculator",
    "one-rep-max",
    "sleep-calculator",
    "running-pace",
    "daily-intake",
    "ovulation-calculator",
    "pregnancy-week-calculator",
    "school-grade",
    "kinship-calculator",
    "pet-age",
    "military-discharge-date",
    "anniversary-calculator",
    "milestone-birthday",
    "lunar-solar-converter",
    "zodiac-sign",
    "traffic-fine-penalty",
    "vehicle-inspection-period",
    "fuel-cost",
    "blox-fruits-calculator",
    "lineage-classic-hunting-efficiency",
    "lineage-classic-lucky-character",
    "robux-calculator",
    "clash-of-clans-calculator",
    "lol-skill-haste",
    "diablo3-gem-calculator",
    "fc-transfer-fee",
    "win-rate-calculator",
    "draw-probability",
    "edpi-calculator",
    "mouse-sensitivity-converter",
    "text-counter",
    "tip-calculator",
    "poker-equity-calculator",
    "spending-habit-score",
    "salary-vanish-calculator",
    "fire-retirement-age",
    "password-generator",
    "lotto-generator",
    "crypto-investment-growth",
    "kr-etf",
    "coin-profit-calculator",
    "youth-future-savings",
    "survivor-pension",
    "earned-income-tax-credit",
    "kpass-refund",
    "gold-price-calculator",
    "silver-price-calculator",
    "stock-average-price",
    "seller-profit"
  ];

  return popularSlugs
    .map((slug) => calculators.find((calculator) => calculator.slug === slug))
    .filter(Boolean) as CalculatorConfig[];
}

export function getRecentCalculators() {
  const recentSlugs: CalculatorSlug[] = [
    "minimum-wage",
    "unpaid-wage",
    "distance-calculator",
    "derivative-calculator",
    "integral-calculator",
    "quadratic-formula",
    "factoring-calculator",
    "logarithm-calculator",
    "inequality-calculator",
    "password-generator",
    "standard-deviation",
    "bmr-calculator",
    "ideal-weight",
    "one-rep-max",
    "sleep-calculator",
    "running-pace",
    "calorie-calculator",
    "daily-intake",
    "ovulation-calculator",
    "pregnancy-week-calculator",
    "school-grade",
    "kinship-calculator",
    "pet-age",
    "anniversary-calculator",
    "milestone-birthday",
    "lunar-solar-converter",
    "zodiac-sign",
    "traffic-fine-penalty",
    "vehicle-inspection-period",
    "auto-installment",
    "fuel-cost",
    "blox-fruits-calculator",
    "lineage-classic-hunting-efficiency",
    "lineage-classic-lucky-character",
    "robux-calculator",
    "clash-of-clans-calculator",
    "lol-skill-haste",
    "diablo3-gem-calculator",
    "fc-transfer-fee",
    "win-rate-calculator",
    "draw-probability",
    "edpi-calculator",
    "mouse-sensitivity-converter",
    "text-counter",
    "tip-calculator",
    "poker-equity-calculator",
    "spending-habit-score",
    "salary-vanish-calculator",
    "fire-retirement-age",
    "credit-card-payoff",
    "retirement-savings",
    "rental-property-roi",
    "lotto-generator",
    "year-end-tax-settlement",
    "inheritance-tax",
    "earned-income-tax",
    "loan-amortization",
    "apr-calculator",
    "housing-subscription",
    "inflation-calculator",
    "money-value-calculator",
    "roi-calculator",
    "present-value",
    "survivor-pension",
    "youth-leap-account",
    "youth-future-savings",
    "earned-income-tax-credit",
    "kpass-refund",
    "childbirth-grant",
    "isa-tax",
    "card-installment",
    "retirement-income-tax",
    "kr-etf",
    "stock-return",
    "coin-profit-calculator",
    "crypto-investment-growth",
    "gold-price-calculator",
    "silver-price-calculator",
    "adsense-revenue",
    "youtube-ad-revenue",
    "stock-average-price",
    "stock-valuation"
  ];

  return recentSlugs
    .map((slug) => calculators.find((calculator) => calculator.slug === slug))
    .filter(Boolean) as CalculatorConfig[];
}

export function searchCalculators(list: CalculatorConfig[], query: string) {
  const needle = query.trim().toLowerCase();
  if (!needle) return list;

  return list.filter((calculator) => {
    const haystack = [
      calculator.title,
      calculator.description,
      calculator.audience,
      calculator.category,
      calculator.badge,
      ...calculator.keywords
    ]
      .join(" ")
      .toLowerCase();

    return haystack.includes(needle);
  });
}

export function getRelatedCalculators(slug: CalculatorSlug, limit = 4) {
  const target = calculators.find((calculator) => calculator.slug === slug);
  if (!target) return [];

  const sameGroup = calculators.filter(
    (calculator) => calculator.slug !== slug && getCalculatorGroup(calculator.slug) === getCalculatorGroup(slug)
  );

  const scored = sameGroup
    .map((calculator) => {
      const keywordOverlap = calculator.keywords.filter((keyword) => target.keywords.includes(keyword)).length;
      const categoryBonus = calculator.category === target.category ? 1 : 0;
      return { calculator, score: keywordOverlap * 2 + categoryBonus };
    })
    .sort((a, b) => b.score - a.score || a.calculator.title.localeCompare(b.calculator.title, "ko"))
    .slice(0, limit)
    .map((item) => item.calculator);

  return scored;
}
